# DS Lab Assignment 2 - Python Basics

**Name**: Debarun Ghosh \
**Student** ID: 25MDA294 \
**Date**: 25 April 2026

## Q1. Write a Python program that prompts the user for his/her price of a meal in a restaurant, then reports how much GST she has to be paid and total bill amount.
Prompts the user for meal price, reports GST and total bill.

In [ ]:
print("=== GST Calculator ===")
meal_price = float(input("Enter meal price (₹): "))
gst_rate = 0.18
gst = meal_price * gst_rate
total = meal_price + gst
print(f"\nMeal Price : ₹{meal_price:.2f}")
print(f"GST (18%)  : ₹{gst:.2f}")
print(f"Total Bill : ₹{total:.2f}")

=== GST Calculator ===
Enter meal price (₹): 500

Meal Price : ₹500.00
GST (18%)  : ₹90.00
Total Bill : ₹590.00


## Q2. Evaluate the quadratic equation for a given a, b, and c.
Evaluate the quadratic equation for user-given a, b, and c.

In [ ]:
import math

print("=== Quadratic Equation Solver (ax² + bx + c = 0) ===")
a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))

discriminant = b**2 - 4*a*c
print(f"\nDiscriminant = {discriminant}")

if discriminant > 0:
    x1 = (-b + math.sqrt(discriminant)) / (2*a)
    x2 = (-b - math.sqrt(discriminant)) / (2*a)
    print(f"Two real roots: x1 = {x1:.2f}, x2 = {x2:.2f}")
elif discriminant == 0:
    x = -b / (2*a)
    print(f"One real root: x = {x:.2f}")
else:
    real = -b / (2*a)
    imag = math.sqrt(-discriminant) / (2*a)
    print(f"Complex roots: x1 = {real:.2f}+{imag:.2f}i, x2 = {real:.2f}-{imag:.2f}i")

=== Quadratic Equation Solver (ax² + bx + c = 0) ===
Enter a: 1
Enter b: -5
Enter c: 6

Discriminant = 1.0
Two real roots: x1 = 3.00, x2 = 2.00


## Q3. How would we print the "99 Bottles of Beer" song?
User chooses how many verses to print.

In [ ]:
print("=== 99 Bottles of Beer ===")
n = int(input("How many verses to display? (1-99): "))
n = max(1, min(99, n))

print()
for i in range(n, 0, -1):
    b  = lambda x: f"{x} bottle{'s' if x != 1 else ''} of beer"
    print(f"{b(i)} on the wall, {b(i)}.")
    print(f"Take one down and pass it around, {b(i-1)} on the wall.")
    print()

print("No more bottles of beer on the wall, no more bottles of beer.")
print("Go to the store and buy some more, 99 bottles of beer on the wall.")

=== 99 Bottles of Beer ===
How many verses to display? (1-99): 5

5 bottles of beer on the wall, 5 bottles of beer.
Take one down and pass it around, 4 bottles of beer on the wall.

4 bottles of beer on the wall, 4 bottles of beer.
Take one down and pass it around, 3 bottles of beer on the wall.

3 bottles of beer on the wall, 3 bottles of beer.
Take one down and pass it around, 2 bottles of beer on the wall.

2 bottles of beer on the wall, 2 bottles of beer.
Take one down and pass it around, 1 bottle of beer on the wall.

1 bottle of beer on the wall, 1 bottle of beer.
Take one down and pass it around, 0 bottles of beer on the wall.

No more bottles of beer on the wall, no more bottles of beer.
Go to the store and buy some more, 99 bottles of beer on the wall.


## Q4. Write a Python program that computes the factorial of an integer.
Computes the factorial of a user-entered integer.

In [ ]:
print("=== Factorial Calculator ===")
n = int(input("Enter a non-negative integer: "))

if n < 0:
    print("Factorial is not defined for negative numbers.")
else:
    result = 1
    for i in range(2, n + 1):
        result *= i
    print(f"\n{n}! = {result}")

=== Factorial Calculator ===
Enter a non-negative integer: 100

100! = 93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


## Q5. Write code to display and count the factors of a number.
Displays and counts all factors of a user-entered number.

In [ ]:
print("=== Factor Finder ===")
n = int(input("Enter a positive integer: "))

factors = [i for i in range(1, n + 1) if n % i == 0]

print(f"\nFactors of {n}: {factors}")
print(f"Total count : {len(factors)}")

=== Factor Finder ===
Enter a positive integer: 133

Factors of 133: [1, 7, 19, 133]
Total count : 4


## Q6. Create a 2D Numpy array and extract a subarray
User enters array size; program creates array and extracts a subarray.

In [ ]:
import numpy as np

print("=== 2D NumPy Array & Subarray ===")
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of cols: "))

arr = np.arange(1, rows * cols + 1).reshape(rows, cols)
print("\nOriginal Array:")
print(arr)

print("\nEnter subarray range (0-indexed):")
r1 = int(input("  Row start   : "))
r2 = int(input("  Row end     : "))
c1 = int(input("  Col start   : "))
c2 = int(input("  Col end     : "))

subarray = arr[r1:r2, c1:c2]
print(f"\nSubarray arr[{r1}:{r2}, {c1}:{c2}]:")
print(subarray)

=== 2D NumPy Array & Subarray ===
Enter number of rows: 3
Enter number of cols: 3

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Enter subarray range (0-indexed):
  Row start   : 1
  Row end     : 3
  Col start   : 1
  Col end     : 3

Subarray arr[1:3, 1:3]:
[[5 6]
 [8 9]]


## Q7. Modify elements using slicing and broadcasting.
User picks a row to zero-out and a column to add a value to.

In [ ]:
import numpy as np

print("=== Slicing & Broadcasting ===")
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of cols: "))

arr = np.arange(1, rows * cols + 1).reshape(rows, cols)
print("\nOriginal Array:")
print(arr)

row_idx = int(input(f"\nEnter row index to set to 0 (0 to {rows-1}): "))
arr[row_idx, :] = 0
print(f"After setting row {row_idx} to 0 (slicing):")
print(arr)

col_idx = int(input(f"\nEnter col index to broadcast add (0 to {cols-1}): "))
val = int(input("Enter value to add: "))
arr[:, col_idx] += val
print(f"After adding {val} to column {col_idx}:")
print(arr)

=== Slicing & Broadcasting ===
Enter number of rows: 3
Enter number of cols: 3

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Enter row index to set to 0 (0 to 2): 2
After setting row 2 to 0 (slicing):
[[1 2 3]
 [4 5 6]
 [0 0 0]]

Enter col index to broadcast add (0 to 2): 1
Enter value to add: 10
After adding 10 to column 1:
[[ 1 12  3]
 [ 4 15  6]
 [ 0 10  0]]


## Q8. Create a dataframe with name, age and marks.
User enters student records; program builds and displays a DataFrame.

In [ ]:
import pandas as pd

print("=== Create Student DataFrame ===")
n = int(input("How many students to enter? "))

names, ages, marks = [], [], []
for i in range(n):
    print(f"\n--- Student {i+1} ---")
    names.append(input("  Name  : "))
    ages.append(int(input("  Age   : ")))
    marks.append(float(input("  Marks : ")))

df = pd.DataFrame({'name': names, 'age': ages, 'marks': marks})
print("\nDataFrame:")
print(df)

=== Create Student DataFrame ===
How many students to enter? 4

--- Student 1 ---
  Name  : Deb
  Age   : 25
  Marks : 88

--- Student 2 ---
  Name  : Adam
  Age   : 24
  Marks : 55

--- Student 3 ---
  Name  : Sam
  Age   : 18
  Marks : 66

--- Student 4 ---
  Name  : Carl
  Age   : 23
  Marks : 87

DataFrame:
   name  age  marks
0   Deb   25   88.0
1  Adam   24   55.0
2   Sam   18   66.0
3  Carl   23   87.0


## Q9. Filter students with marks > 80, sort by age.

In [ ]:
import pandas as pd

print("=== Filter & Sort DataFrame ===")
n = int(input("How many students to enter? "))

names, ages, marks = [], [], []
for i in range(n):
    print(f"\n--- Student {i+1} ---")
    names.append(input("  Name  : "))
    ages.append(int(input("  Age   : ")))
    marks.append(float(input("  Marks : ")))

df = pd.DataFrame({'name': names, 'age': ages, 'marks': marks})

threshold = float(input("\nEnter marks threshold to filter (e.g. 80): "))
filtered = df[df['marks'] > threshold].sort_values('age').reset_index(drop=True)

print(f"\nStudents with marks > {threshold}, sorted by age:")
print(filtered)

=== Filter & Sort DataFrame ===
How many students to enter? 4

--- Student 1 ---
  Name  : Deb
  Age   : 25
  Marks : 88

--- Student 2 ---
  Name  : Sam
  Age   : 24
  Marks : 55

--- Student 3 ---
  Name  : Carlson
  Age   : 44
  Marks : 35

--- Student 4 ---
  Name  : Ram
  Age   : 33
  Marks : 48

Enter marks threshold to filter (e.g. 80): 50

Students with marks > 50.0, sorted by age:
  name  age  marks
0  Sam   24   55.0
1  Deb   25   88.0


## Q10. Export the filtered Dataframe to csv.

In [ ]:
import pandas as pd

print("=== Export Filtered DataFrame to CSV ===")
n = int(input("How many students to enter? "))

names, ages, marks = [], [], []
for i in range(n):
    print(f"\n--- Student {i+1} ---")
    names.append(input("  Name  : "))
    ages.append(int(input("  Age   : ")))
    marks.append(float(input("  Marks : ")))

df = pd.DataFrame({'name': names, 'age': ages, 'marks': marks})

threshold = float(input("\nEnter marks threshold to filter (e.g. 80): "))
filtered = df[df['marks'] > threshold].sort_values('age').reset_index(drop=True)

filename = input("Enter output CSV filename (e.g. result.csv): ").strip()
if not filename.endswith('.csv'):
    filename += '.csv'

filtered.to_csv(filename, index=False)
print(f"\nExported {len(filtered)} record(s) to '{filename}'")
print(filtered)

=== Export Filtered DataFrame to CSV ===
How many students to enter? 5

--- Student 1 ---
  Name  : Deb
  Age   : 25
  Marks : 66

--- Student 2 ---
  Name  : Adi
  Age   : 24
  Marks : 65

--- Student 3 ---
  Name  : Raj
  Age   : 23
  Marks : 55

--- Student 4 ---
  Name  : Sham
  Age   : 23
  Marks : 42

--- Student 5 ---
  Name  : Rom
  Age   : 22
  Marks : 56

Enter marks threshold to filter (e.g. 80): 44
Enter output CSV filename (e.g. result.csv): output

Exported 4 record(s) to 'output.csv'
  name  age  marks
0  Rom   22   56.0
1  Raj   23   55.0
2  Adi   24   65.0
3  Deb   25   66.0
